### ISSUE TITLE
Support binary data files

### ISSUE THREAD

**Issue by biiiipy** [microsoft/vscode-data-analysis-for-copilot#75]
Please add support for parquet and similar file formats for data analysis.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, out of curiosity, what happens when you do try to use such a file in your prompt?

**Comment by DonJayamanne** [comment]
@biiiipy I managed to replicate this issue and believe we have a solution for this.

**Comment by DonJayamanne** [comment]
@biiiipy please do try the new version and please let me know if this works or not, I've tested this at my end and it works
